export const paths = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  COMMON_COMPONENTS: '/common-components',
  STUDENT_SHOP: '/shop',
  TEACHER_SHOP: '/shop/teacher',
  TEACHER_MISSION: '/mission/teacher',
  STUDENT_MISSION: '/mission',
  STUDENT_STOCK: '/stock',
  DESIGN_SYSTEM: '/design-system',
  TEACHER_CLASSROOM: '/classroom/teacher',
  STUDENT_CLASSROOM: '/classroom',
  STUDENT_DASHBOARD: '/dashboard',
} as const;
